services:
  ollama-1:
    image: ollama/ollama:latest
    container_name: ollama-1
    ports:
      - "11434:11434"
    volumes:
      - ../../backend/backup-1:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama-2:
    image: ollama/ollama:latest
    container_name: ollama-2
    ports:
      - "11435:11434"
    volumes:
      - ../../backend/backup-2:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # ollama-3:
  #   image: ollama/ollama:latest
  #   container_name: ollama-3
  #   ports:
  #     - "11436:11434"
  #   volumes:
  #     - ../../backend/backup-3:/root/.ollama
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]